#!/usr/bin/env python3
"""Sync one Intake-v2 Incubator problem into Problems workspace."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


SUITE_ALIAS = {
    "rl": "RL",
    "llm": "LLM",
    "ai": "AI",
    "or": "OR",
    "oco": "OCO",
}


def slug_to_module(raw: str) -> str:
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in raw).strip("_")
    if not cleaned:
        raise ValueError(f"invalid empty identifier from `{raw}`")
    parts = [p for p in cleaned.split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)


def suite_from_domain(domain: str) -> str:
    did = domain.strip().lower()
    if not did:
        return "Learning"
    if did in SUITE_ALIAS:
        return SUITE_ALIAS[did]
    return "".join(p[:1].upper() + p[1:] for p in did.split("_") if p)


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def copy_file(src: Path, dst: Path) -> bool:
    if not src.exists():
        return False
    ensure_parent(dst)
    shutil.copy2(src, dst)
    return True


def write_if_missing(path: Path, content: str) -> bool:
    if path.exists():
        return False
    ensure_parent(path)
    path.write_text(content, encoding="utf-8")
    return True


def render_proof_template(suite: str, problem_mod: str) -> str:
    namespace = f"Problems.{suite}.{problem_mod}"
    return (
        f"import Problems.{suite}.{problem_mod}.Cache\n\n"
        f"namespace {namespace}\n\n"
        "/-- Auto-generated proof workspace entry.\n"
        "Replace this with the final readable proof skeleton. -/\n"
        "theorem workspaceProofReady : True := by\n"
        "  trivial\n\n"
        f"end {namespace}\n"
    )


def rewrite_problems_root_index(repo_root: Path) -> None:
    problems_root = repo_root / "Problems"
    imports: list[str] = []
    for proof in sorted(problems_root.rglob("Proof.lean")):
        rel = proof.relative_to(problems_root)
        if len(rel.parts) != 3:
            continue
        suite, problem, _ = rel.parts
        imports.append(f"import Problems.{suite}.{problem}.Proof")

    header = (
        "-- GENERATED by tools/intake/sync_problem_workspace.py\n"
        "-- Keep this file import-only.\n"
    )
    body = "\n".join(imports).strip()
    text = header + ("\n" + body + "\n" if body else "\n")
    (repo_root / "Problems.lean").write_text(text, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-root", default=".", help="MLTheory repo root")
    ap.add_argument("--domain", required=True, help="domain id (e.g., rl)")
    ap.add_argument("--problem", required=True, help="problem slug/name")
    ap.add_argument("--suite", default="", help="override Problems suite name")
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()

    domain_mod = slug_to_module(args.domain)
    problem_mod = slug_to_module(args.problem)
    suite = args.suite.strip() or suite_from_domain(args.domain)

    inc_root = repo_root / "Incubator" / domain_mod / problem_mod
    if not inc_root.exists():
        raise RuntimeError(f"incubator problem not found: {inc_root}")

    prob_root = repo_root / "Problems" / suite / problem_mod
    prob_root.mkdir(parents=True, exist_ok=True)

    copied = 0
    for src_name, dst_name in (
        ("Spec.lean", "Spec.lean"),
        ("Cache.lean", "Cache.lean"),
        ("Sketch.lean", "Sketch.lean"),
        ("Tasks.yaml", "Tasks.yaml"),
    ):
        if copy_file(inc_root / src_name, prob_root / dst_name):
            copied += 1

    if copy_file(inc_root / "research" / "sources.md", prob_root / "Sources.md"):
        copied += 1
    if copy_file(inc_root / "research" / "glossary.yaml", prob_root / "Glossary.yaml"):
        copied += 1

    if copy_file(inc_root / "Proof.lean", prob_root / "Proof.lean"):
        copied += 1
    else:
        if write_if_missing(prob_root / "Proof.lean", render_proof_template(suite, problem_mod)):
            copied += 1

    rewrite_problems_root_index(repo_root)
    print(
        "[sync_problem_workspace] synced "
        f"Incubator/{domain_mod}/{problem_mod} -> Problems/{suite}/{problem_mod} "
        f"(files_updated={copied})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
