#!/usr/bin/env python3
"""Generate docs/_auto/subgraph.js for file:// GraphExplorer fallback."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--subgraph", type=Path, required=True, help="source subgraph.json")
    ap.add_argument("--out", type=Path, required=True, help="output JS file")
    args = ap.parse_args()

    payload = json.loads(args.subgraph.read_text(encoding="utf-8"))
    out = args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    js = (
        "// GENERATED BY tools/index/gen_subgraph_js.py. DO NOT EDIT MANUALLY.\n"
        "window.__MLTHEORY_SUBGRAPH__ = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    out.write_text(js, encoding="utf-8")
    print(f"[gen_subgraph_js] wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
