#!/usr/bin/env python3
"""Render docs/_auto markdown from index artifacts."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


GENERATED_NOTE = "<!-- GENERATED BY tools/index/render_auto_docs.py. DO NOT EDIT MANUALLY. -->"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def md_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(["---"] * len(headers)) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--modules", type=Path, required=True, help="modules.json path")
    ap.add_argument("--imports", type=Path, required=True, help="imports.json path")
    ap.add_argument("--out", type=Path, required=True, help="Output markdown path")
    args = ap.parse_args()

    modules_data = load_json(args.modules.resolve())
    imports_data = load_json(args.imports.resolve())

    modules = modules_data.get("modules", [])
    fan_out_raw = imports_data.get("fan_out", {})
    fan_in_raw = imports_data.get("fan_in", {})
    fan_out = {k: int(v) for k, v in fan_out_raw.items()} if isinstance(fan_out_raw, dict) else {}
    fan_in = {k: int(v) for k, v in fan_in_raw.items()} if isinstance(fan_in_raw, dict) else {}

    layer_counter = Counter(m.get("layer", "other") for m in modules if isinstance(m, dict))
    top_out = sorted(fan_out.items(), key=lambda kv: (-kv[1], kv[0]))[:15]
    top_in = sorted(fan_in.items(), key=lambda kv: (-kv[1], kv[0]))[:15]

    lines = [
        "# Code Index（自动生成）",
        "",
        GENERATED_NOTE,
        "",
        "## 统计",
        f"- 生成日期：`{modules_data.get('generated_at', '-')}`",
        f"- 模块数：`{modules_data.get('module_count', len(modules))}`",
        f"- import 边数：`{imports_data.get('edge_count', '-')}`",
        "",
        "## 按层分布",
        md_table(
            ["layer", "count"],
            [[layer, str(count)] for layer, count in sorted(layer_counter.items())],
        ),
        "",
        "## Fan-out Top 15",
        md_table(
            ["module", "fan_out"],
            [[module, str(score)] for module, score in top_out] or [["（空）", "0"]],
        ),
        "",
        "## Fan-in Top 15",
        md_table(
            ["module", "fan_in"],
            [[module, str(score)] for module, score in top_in] or [["（空）", "0"]],
        ),
        "",
        "## 一键更新命令",
        "```bash",
        "tools/index/gen_mltheory_index.sh",
        "```",
        "",
    ]

    out = args.out.resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[render_auto_docs] wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
