#!/usr/bin/env python3
"""Render docs/_auto graph summary from graph artifacts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


GENERATED_NOTE = "<!-- GENERATED BY tools/index/render_graph_auto_docs.py. DO NOT EDIT MANUALLY. -->"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--subgraph", type=Path, required=True, help="subgraph.json path")
    ap.add_argument("--usage-graph", type=Path, required=True, help="usage_graph.json path")
    ap.add_argument("--usage-suggestions", type=Path, required=True, help="usage_suggestions.json path")
    ap.add_argument("--out", type=Path, required=True, help="output markdown path")
    args = ap.parse_args()

    subgraph = load_json(args.subgraph.resolve())
    usage_graph = load_json(args.usage_graph.resolve())
    usage_suggestions = load_json(args.usage_suggestions.resolve())

    top_spine = usage_suggestions.get("spine_candidates", [])[:15]
    top_modules = usage_suggestions.get("entry_module_candidates", [])[:15]

    lines = [
        "# Graph Artifacts(Automatically generated)",
        "",
        GENERATED_NOTE,
        "",
        "## statistics",
        f"- subgraph nodes: `{subgraph.get('node_count', 0)}`",
        f"- subgraph edges: `{subgraph.get('edge_count', 0)}`",
        f"- usage events: `{usage_graph.get('event_count', 0)}`",
        f"- usage nodes: `{usage_graph.get('node_count', 0)}`",
        f"- usage edges: `{usage_graph.get('edge_count', 0)}`",
        "",
        "## Telemetry driven spine candidate(Top 15)",
        table(["decl"], [[d] for d in top_spine] or [["(null)"]]),
        "",
        "## Telemetry Driver entry module candidate(Top 15)",
        table(["module"], [[m] for m in top_modules] or [["(null)"]]),
        "",
        "## One-click update command",
        "```bash",
        "tools/index/gen_graph_artifacts.sh",
        "```",
        "",
    ]

    out = args.out.resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[render_graph_auto_docs] wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
